[package]
name = "test-macros"
version = "0.1.0"
edition = "2024"
description = "Internal macros that help with testss"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.101"
quote = { workspace = true }
syn = { workspace = true }
