[package]
name = "rholang-fake"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
async-std = { workspace = true }
