[package]
name = "rholang-lib"
description = "Library utilities for Rholang"
version = "0.1.0"
edition = "2024"

[lib]
name = "librho"
crate-type = ["cdylib", "rlib"]
edition = "2024"

[dependencies]
by_address = "1.2.1"
indexmap = "2.11.0"
rholang-parser = { path = "../rholang-parser" }
smallvec = { workspace = true }
