[package]
name = "rholang-parser-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rholang-parser = { path = "../rholang-parser" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
