[package]
name = "rholang-parser-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rholang-parser = { path = "../rholang-parser" }
anyhow = { workspace = true }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
clap = { workspace = true }
